### ISSUE TITLE
support newer versions of czmq?

### ISSUE THREAD

**Issue by exquisitus** [lhope/cl-czmq#1]
Hello. Visiting the czmq site, I read:
- The current stable release is v3.0.2. We recommend this release for new development, as it has a simpler and cleaner socket API. Main changes over v2.2: smart sockets (zsock), actors (zactor), gossip discovery (zgossip), regexps (xrex), and process management (in zsys).
- The previous stable release was v2.2.0.

Your readme page says that cl-czmq has been tested to work with czmq 1.4.1, but mentions nothing of the newer versions. Is there a chance you will support them in the future, or maybe even a chance that cl-czmq actually works now with one of those newer versions?

**Comment by lhope** [comment]
Hi there, and thanks for your interest.

I am confident the current codebase will NOT work with later versions of ZMQ/CZMQ.

When I last looked at this, v2 was coming in, and CZMQ was very much a moving target. To do a good job on CZMQ at that stage, a lot of work had to go in to porting the code, not just wrapping it. I was quite busy at the time, and I could see that I would just be putting work in to have it obsoleted within a month or so.

It seems that CZMQ may be more stable now, but even if this is so, I can't see myself putting the energy in to write anything like a full implementation/wrapper.

I have thought about dipping into this again, and my thought is to write either a trivial-zmq or trivial-czmq library which just deals with the messaging at a low level, and pair this with a library which can interact with devices written in C (such as majordomo, for example). Perhaps some of the code in this library could be re-used in this case.

But at present, the answer to your question is no. Sorry.

**Comment by exquisitus** [comment]
Thank you for your answer. I think you made the only reasonable decision. I have also investigated three 0MQ libraries, lisp-zmq, cl-zmq, pzmq and I guess now that none of them is actually maintained. ZeroMQ is moving forward with a 4.1 version my conclusion is that the Common LISP community is simply too small to make it worth it.
There is excellent documentation and example code for the project in C, and Common LISP programmers should probably just learn how to write some C code and how to call this code from LISP. One can't really avoid it because a similar situation (with unmaintained or non-existent LISP bindings) exists for many other useful libraries written in C.
